version: '3'

services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: ./hyperf-app/
    volumes:
      - ./hyperf-app/:/opt/www
    ports:
      - "9501:9501"
      - "9502:9502"
    networks:
      - app-network
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  application-db:
    container_name: application-db
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "db"

  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    networks:
      - app-network
    ports:
      - 6379:6379

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./laravel/.docker/nginx:/etc/nginx/conf.d
      - ./laravel/.docker/nginx/laravel-app.conf:/etc/nginx/sites-available/laravel-app
      - ./laravel/.docker/nginx/laravel-app.conf:/etc/nginx/sites-enabled/laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: ./laravel/.docker/php
      dockerfile: Dockerfile
    container_name: laravel
    networks:
      - app-network
    volumes:
      - ./laravel/:/var/www
      - ./laravel/.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  websocket-client:
    build:
      context: ./front-end/websocket-client
      dockerfile: Dockerfile
    container_name: websocket-client
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge
